### ISSUE TITLE
[FEATURE} Equipped items' background reflecting the item's rarity color

### ISSUE THREAD

**Issue by Sad-theFaceless** [Tmktahu/WakForge#140]
Currently, the background is purple for all the equipped items. It could be better to have their rarity's color (white, green, orange, yellow, blue, pink or purple) instead, in order to not have to mouse-over the item to see which one it is.

**Comment by Tmktahu** [comment]
There was a similar request to better reflect the item's rarity down in the item list as well. I'll add this to the priority list and see what I can come up with.

**Comment by Tmktahu** [comment]
Added in #149
