### ISSUE TITLE
Negative Crit Bug

### ISSUE THREAD

**Issue by alek-mcgarry** [Tmktahu/WakForge#98]
By default units have 3% crit
If I equip just Ogrest's Wrath with -10% crit the expected result is -7% crit
The actual result is -8% crit
![image](https://github.com/Tmktahu/WakForge/assets/29163645/b60d28b3-9f52-48b2-bc97-feb72adec926)

If I equal another -10% crit item like Zinit Hat it corrects itself, it goes from -8% -> - 17%
![image](https://github.com/Tmktahu/WakForge/assets/29163645/6860c011-4d7d-43e1-8814-14f11a5eba5e)

**Comment by Tmktahu** [comment]
@alek-mcgarry nice catch. I think it's a rounding error. Normally the game rounds numbers down, but in this case rounding 'down' is rounding to -8 when the actual value is probably -7.?? or something.

I'll poke some people to see how wakfu seems to round negative numbers. I may have to round up if the value is negative or something.

**Comment by Tmktahu** [comment]
Yea I think there is a minimum -crit you can have.

And yea I can't think of any multipliers that would result in a decimal part either. I'm performing some rounding in the website to handle a few function math precision problems that crept up. It shouldn't be hard to tweak the logic to handle this properly

**Comment by Tmktahu** [comment]
@alek-mcgarry alright just pushed up a fix for the problem in the above PR. If things look good on your end, feel free to close this issue.
